name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - run: python printing.py
      - name: Run Unit Tests
        run: echo "Running unit tests"

  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - run: python printing.py
      - name: Lint Code
        run: echo "Linting code"

  job3:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - run: python printing.py
      - name: Build Project
        run: echo "Building project"
  job4:
    runs-on: ubuntu-latest
    needs: [job2, job3]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - run: python printing.py
      - name: Build Project
        run: echo "Building project"
